1. Creating a DataFrame from a Dictionary

In [386]:
import pandas as pd
import numpy as np

In [387]:
dict={"num":(0,1,2,3,4,5,6,7,8,9),
      "Even":(2,4,6,8,10,12,14,16,18,20),
      "Odd":(1,3,5,7,9,11,13,15,17,19)}
df=pd.DataFrame(data=dict)
df

   num  Even  Odd
0    0     2    1
1    1     4    3
2    2     6    5
3    3     8    7
4    4    10    9
5    5    12   11
6    6    14   13
7    7    16   15
8    8    18   17
9    9    20   19

2. DataFrame with Specified Index Labels

In [388]:
dict={"Name":("Sanya","Anmol","Manya","Riya","Garima","Aman"),
      "RollNum":(2412201,2412202,2412203,2412204,2412205,2412206),
      "Score":(67,89,97,np.nan,75,87),
      "Attempts":(2,3,1,5,6,3),
      "Qualify":("yes","yes","yes","no","yes","yes"),
      "city":("kanpur","kanpur","lucknow","kanpur","lucknow","kanpur")}
df=pd.DataFrame(dict,index=["a","b","c","d","e","f"])
df

     Name  RollNum  Score  Attempts Qualify     city
a   Sanya  2412201   67.0         2     yes   kanpur
b   Anmol  2412202   89.0         3     yes   kanpur
c   Manya  2412203   97.0         1     yes  lucknow
d    Riya  2412204    NaN         5      no   kanpur
e  Garima  2412205   75.0         6     yes  lucknow
f    Aman  2412206   87.0         3     yes   kanpur

3. DataFrame Basic Summary Information

In [389]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   RollNum   6 non-null      int64
 2   Score     5 non-null      float64
 3   Attempts  6 non-null      int64
 4   Qualify   6 non-null      object
 5   city      6 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 336.0+ bytes

4. Selecting the First 3 Rows

In [390]:
df[:3]

    Name  RollNum  Score  Attempts Qualify     city
a  Sanya  2412201   67.0         2     yes   kanpur
b  Anmol  2412202   89.0         3     yes   kanpur
c  Manya  2412203   97.0         1     yes  lucknow

5. Selecting 'name' and 'score' Columns

In [391]:
df[["Name","Score"]]

     Name  Score
a   Sanya   67.0
b   Anmol   89.0
c   Manya   97.0
d    Riya    NaN
e  Garima   75.0
f    Aman   87.0

6. Selecting Specific Columns and Rows

In [392]:
##df.iloc[start_row:end_row,start_col:end_col]
df.iloc[0:2,1:2]

   RollNum
a  2412201
b  2412202

7. Selecting Rows Where score>90

In [393]:
df[df["Score"]>90]

    Name  RollNum  Score  Attempts Qualify     city
c  Manya  2412203   97.0         1     yes  lucknow

8. Counting Rows and Columns

In [394]:
df.shape
#df.shape=(row,column)

(6, 6)

9. Selecting Rows with Missing Score

In [395]:
df[df["Score"].isnull()]

   Name  RollNum  Score  Attempts Qualify    city
d  Riya  2412204    NaN         5      no  kanpur

10. Selecting Rows Where Score is Between 15 and 20

In [396]:
df[df["Score"].between(15,20)]

Empty DataFrame
Columns: [Name, RollNum, Score, Attempts, Qualify, city]
Index: []

11. Selecting Rows with Attempts > 2 and Score > 80

In [397]:
df[(df["Attempts"]<2 ) & (df["Score"]>80)]

    Name  RollNum  Score  Attempts Qualify     city
c  Manya  2412203   97.0         1     yes  lucknow

12. Changing the Score in a Specific Row
Write a Pandas program to change the score in row 'd' to 11.5.

In [398]:
df.loc["d","Score"]=11.5
df

     Name  RollNum  Score  Attempts Qualify     city
a   Sanya  2412201   67.0         2     yes   kanpur
b   Anmol  2412202   89.0         3     yes   kanpur
c   Manya  2412203   97.0         1     yes  lucknow
d    Riya  2412204   11.5         5      no   kanpur
e  Garima  2412205   75.0         6     yes  lucknow
f    Aman  2412206   87.0         3     yes   kanpur

3. Summing Examination Attempts

In [399]:
df["Attempts"].sum()

np.int64(20)

14. Calculating the Mean of Scores

In [400]:
df["Score"].mean()

np.float64(71.08333333333333)

15. Appending and Deleting a New Row

In [401]:
print("Appending a New Row")
df.loc["g"]=("Rakesh",2412207,"yes",56,2)
df

Appending a New Row

ValueError: cannot set a row with mismatched columns

In [ ]:
print("Deleting Row")
df.drop("a")

Deleting Row

     Name  RollNum Score  Attempts Qualify
b   Anmol  2412202  89.0         3     yes
c   Manya  2412203  97.0         1     yes
d    Riya  2412204  11.5         5      no
e  Garima  2412205  75.0         6     yes
f    Aman  2412206  87.0         3     yes
g  Rakesh  2412207   yes        56       2

16. Sorting the DataFrame by Multiple Columns

In [ ]:
df.sort_index(ascending=False)

     Name  RollNum Score  Attempts Qualify
g  Rakesh  2412207   yes        56       2
f    Aman  2412206  87.0         3     yes
e  Garima  2412205  75.0         6     yes
d    Riya  2412204  11.5         5      no
c   Manya  2412203  97.0         1     yes
b   Anmol  2412202  89.0         3     yes
a   Sanya  2412201  67.0         2     yes

In [ ]:
df.sort_values(by="Name",ascending=False)

     Name  RollNum Score  Attempts Qualify
a   Sanya  2412201  67.0         2     yes
d    Riya  2412204  11.5         5      no
g  Rakesh  2412207   yes        56       2
c   Manya  2412203  97.0         1     yes
e  Garima  2412205  75.0         6     yes
b   Anmol  2412202  89.0         3     yes
f    Aman  2412206  87.0         3     yes

17. Replacing Column Values (qualify)

In [ ]:
df["Qualify"]=df["Qualify"].map({"yes":True,"no":False})
df

     Name  RollNum Score  Attempts Qualify
a   Sanya  2412201  67.0         2    True
b   Anmol  2412202  89.0         3    True
c   Manya  2412203  97.0         1    True
d    Riya  2412204  11.5         5   False
e  Garima  2412205  75.0         6    True
f    Aman  2412206  87.0         3    True
g  Rakesh  2412207   yes        56     NaN

18. Changing a Specific Name Value

In [ ]:
df["Name"]=df["Name"].replace({"Sanya":"Sanya Katiyar"})
df

            Name  RollNum Score  Attempts Qualify
a  Sanya Katiyar  2412201  67.0         2    True
b          Anmol  2412202  89.0         3    True
c          Manya  2412203  97.0         1    True
d           Riya  2412204  11.5         5   False
e         Garima  2412205  75.0         6    True
f           Aman  2412206  87.0         3    True
g         Rakesh  2412207   yes        56     NaN

19. Deleting a Column from the DataFrame

In [ ]:
df.drop("Score",axis=1,inplace=True)

20. Inserting a New Column

In [ ]:
df["Marks"]=(6.7,5.9,9.0,7.6,4.6,8.7,6.7)
df

            Name  RollNum  Attempts Qualify  Marks
a  Sanya Katiyar  2412201         2    True    6.7
b          Anmol  2412202         3    True    5.9
c          Manya  2412203         1    True    9.0
d           Riya  2412204         5   False    7.6
e         Garima  2412205         6    True    4.6
f           Aman  2412206         3    True    8.7
g         Rakesh  2412207        56     NaN    6.7

22. Getting List from Column Headers

In [ ]:
df.columns

Index(['Name', 'RollNum', 'Attempts', 'Qualify', 'Marks'], dtype='object')

23. Renaming DataFrame Columns

In [ ]:
df.rename(columns={"Name": "Student_name"})

    Student_name  RollNum  Attempts Qualify  Marks
a  Sanya Katiyar  2412201         2    True    6.7
b          Anmol  2412202         3    True    5.9
c          Manya  2412203         1    True    9.0
d           Riya  2412204         5   False    7.6
e         Garima  2412205         6    True    4.6
f           Aman  2412206         3    True    8.7
g         Rakesh  2412207        56     NaN    6.7

24. Selecting Rows Based on Column Values

In [ ]:
df[df["Marks"]<=6.0]

     Name  RollNum  Attempts Qualify  Marks
b   Anmol  2412202         3    True    5.9
e  Garima  2412205         6    True    4.6

In [ ]:
df

            Name  RollNum  Attempts Qualify  Marks
a  Sanya Katiyar  2412201         2    True    6.7
b          Anmol  2412202         3    True    5.9
c          Manya  2412203         1    True    9.0
d           Riya  2412204         5   False    7.6
e         Garima  2412205         6    True    4.6
f           Aman  2412206         3    True    8.7
g         Rakesh  2412207        56     NaN    6.7

25. Changing the Order of DataFrame Columns

26. Add One Row to a DataFrame

In [ ]:
df.loc["k"]=("Neha",2412208,1,False,2.1)
df

            Name  RollNum  Attempts Qualify  Marks
a  Sanya Katiyar  2412201         2    True    6.7
b          Anmol  2412202         3    True    5.9
c          Manya  2412203         1    True    9.0
d           Riya  2412204         5   False    7.6
e         Garima  2412205         6    True    4.6
f           Aman  2412206         3    True    8.7
g         Rakesh  2412207        56     NaN    6.7
k           Neha  2412208         1   False    2.1

27. Write DataFrame to CSV (Tab Separator)

In [ ]:
df.to_csv("new file",sep="\t")
pd.read_csv("new file")

  \tName\tRollNum\tAttempts\tQualify\tMarks
0   a\tSanya Katiyar\t2412201\t2\tTrue\t6.7
1           b\tAnmol\t2412202\t3\tTrue\t5.9
2           c\tManya\t2412203\t1\tTrue\t9.0
3           d\tRiya\t2412204\t5\tFalse\t7.6
4          e\tGarima\t2412205\t6\tTrue\t4.6
5            f\tAman\t2412206\t3\tTrue\t8.7
6             g\tRakesh\t2412207\t56\t\t6.7
7           k\tNeha\t2412208\t1\tFalse\t2.1

28. City Wise Count

In [ ]:
df.groupby(["city"]).size().reset_index(name="num of people in city")

      city  num of people in city
0   kanpur                      4
1  lucknow                      2

32. Replace NaN with Zeros

In [ ]:
df.fillna(0)

     Name  RollNum  Score  Attempts Qualify     city
a   Sanya  2412201   67.0         2     yes   kanpur
b   Anmol  2412202   89.0         3     yes   kanpur
c   Manya  2412203   97.0         1     yes  lucknow
d    Riya  2412204   11.5         5      no   kanpur
e  Garima  2412205   75.0         6     yes  lucknow
f    Aman  2412206   87.0         3     yes   kanpur

35. Count NaN Values

In [ ]:
df.isna().sum()

Name        0
RollNum     0
Score       0
Attempts    0
Qualify     0
city        0
dtype: int64

36. Drop Rows from DataFrame

In [ ]:
df.drop("b",inplace=True)
df

     Name  RollNum  Score  Attempts Qualify     city
a   Sanya  2412201   67.0         2     yes   kanpur
c   Manya  2412203   97.0         1     yes  lucknow
d    Riya  2412204   11.5         5      no   kanpur
e  Garima  2412205   75.0         6     yes  lucknow
f    Aman  2412206   87.0         3     yes   kanpur

39. Combine Two Series

In [ ]:
s1=pd.Series(("Sanya","Manya","Rohit"))
s2=pd.Series((13,45,67))
df2=pd.DataFrame({"name":s1,"num":s2})
df2

    name  num
0  Sanya   13
1  Manya   45
2  Rohit   67

40. Shuffle DataFrame Rows

In [ ]:
pd.random.permutation()

41. String to Datetime

In [ ]:
import datetime 

dates = pd.Series([
    "3/11/2000",
    "3/12/2000",
    "3/13/2000"
])

print("String Date:")
print(dates)
print("\nDatetime:")
dates = pd.to_datetime(dates)
print(dates)

String Date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object

Datetime:
0   2000-03-11
1   2000-03-12
2   2000-03-13
dtype: datetime64[ns]


43. Column to List

In [ ]:
df["Name"].to_list()

['Sanya', 'Anmol', 'Manya', 'Riya', 'Garima', 'Aman']

44. DataFrame from NumPy Array

In [ ]:
df.to_numpy()

array([['Sanya', 2412201, 67.0, 2, 'yes', 'kanpur'],
       ['Anmol', 2412202, 89.0, 3, 'yes', 'kanpur'],
       ['Manya', 2412203, 97.0, 1, 'yes', 'lucknow'],
       ['Riya', 2412204, 11.5, 5, 'no', 'kanpur'],
       ['Garima', 2412205, 75.0, 6, 'yes', 'lucknow'],
       ['Aman', 2412206, 87.0, 3, 'yes', 'kanpur']], dtype=object)

45. Row with Maximum Value

In [ ]:
df[["Score","Attempts","RollNum"]].max()

Score            97.0
Attempts          6.0
RollNum     2412206.0
dtype: float64

46. Check Column Presence

In [ ]:
df.isin({"Name": ["Sanya"]}).sum()

Name        1
RollNum     0
Score       0
Attempts    0
Qualify     0
city        0
dtype: int64

48. Get Column DataTypes

In [ ]:
df.sample

<bound method NDFrame.sample of      Name  RollNum  Score  Attempts Qualify     city
a   Sanya  2412201   67.0         2     yes   kanpur
b   Anmol  2412202   89.0         3     yes   kanpur
c   Manya  2412203   97.0         1     yes  lucknow
d    Riya  2412204   11.5         5      no   kanpur
e  Garima  2412205   75.0         6     yes  lucknow
f    Aman  2412206   87.0         3     yes   kanpur>

53. Insert Column at Specific Index

In [405]:
df["col1"]=(1,2,3,4,5,6)
df.drop("col1", axis=1, inplace=True)
df
df["col1"]=(1,2,3,4,5,6)
df

     Name  RollNum  Score  Attempts Qualify     city  col1
a   Sanya  2412201   67.0         2     yes   kanpur     1
b   Anmol  2412202   89.0         3     yes   kanpur     2
c   Manya  2412203   97.0         1     yes  lucknow     3
d    Riya  2412204   11.5         5      no   kanpur     4
e  Garima  2412205   75.0         6     yes  lucknow     5
f    Aman  2412206   87.0         3     yes   kanpur     6