#### Joining and merging DataFrame

1. Join DataFrames along Rows (Join Rows)

In [73]:
import pandas as pd

# Student DataFrame 1
student_data1 = pd.DataFrame({
    "student_id": ["S1", "S2", "S3", "S4", "S5"],
    "name": [
        "Danniella Fenton",
        "Ryder Storey",
        "Bryce Jensen",
        "Ed Bernal",
        "Kwame Morin"
    ],
    "marks": [200, 210, 190, 222, 199]
})

# Student DataFrame 2
student_data2 = pd.DataFrame({
    "student_id": ["S4", "S5", "S6", "S7", "S8"],
    "name": [
        "Scarlette Fisher",
        "Carla Williamson",
        "Dante Morse",
        "Kaiser William",
        "Madeeha Preston"
    ],
    "marks": [201, 200, 198, 219, 201]
})

# Display DataFrames
print("student_data1:")
print(student_data1)

print("\nstudent_data2:")
print(student_data2)

student_data1:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199

student_data2:
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

In [74]:
pd.concat([student_data1,student_data2])

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

2. Join DataFrames along Columns (Join Columns)

In [75]:
pd.concat([student_data1,student_data2],axis=1)

  student_id              name  marks student_id              name  marks
0         S1  Danniella Fenton    200         S4  Scarlette Fisher    201
1         S2      Ryder Storey    210         S5  Carla Williamson    200
2         S3      Bryce Jensen    190         S6       Dante Morse    198
3         S4         Ed Bernal    222         S7    Kaiser William    219
4         S5       Kwame Morin    199         S8   Madeeha Preston    201

3. Append Rows to Existing DataFrame

In [76]:
student_data1.loc[6]=("S6","Scarlette Fisher",205)
student_data1

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
6         S6  Scarlette Fisher    205

4. Append List of Dictionaries/Series
//append method removed from pd

5. Join Rows and Merge with Another DataFrame

In [77]:
df=pd.concat([student_data1,student_data2])
print(df)
# creatin df
df3 = pd.DataFrame({
    "student_id": ["S9"],
    "name": ["Sanya"],
    "marks": [210]
})

df1=pd.concat([df,df3])
print(df1)

  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
6         S6  Scarlette Fisher    205
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
6         S6  Scarlette Fisher    205
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
0         S9             Sanya    210

6. Join DataFrames Using Common Column –

7. Join with Matching Records (Inner Join)

In [78]:
df=pd.merge(student_data1,student_data2,on="student_id",how="inner")
df

  student_id            name_x  marks_x            name_y  marks_y
0         S4         Ed Bernal      222  Scarlette Fisher      201
1         S5       Kwame Morin      199  Carla Williamson      200
2         S6  Scarlette Fisher      205       Dante Morse      198

8. Left Join Using Keys from Left DataFrame

In [79]:
#using left
pd.merge(student_data1,student_data2,on="student_id",how="left")

  student_id            name_x  marks_x            name_y  marks_y
0         S1  Danniella Fenton      200               NaN      NaN
1         S2      Ryder Storey      210               NaN      NaN
2         S3      Bryce Jensen      190               NaN      NaN
3         S4         Ed Bernal      222  Scarlette Fisher    201.0
4         S5       Kwame Morin      199  Carla Williamson    200.0
5         S6  Scarlette Fisher      205       Dante Morse    198.0

In [80]:
#using right
pd.merge(student_data2,student_data1,on="student_id",how="left")

  student_id            name_x  marks_x            name_y  marks_y
0         S4  Scarlette Fisher      201         Ed Bernal    222.0
1         S5  Carla Williamson      200       Kwame Morin    199.0
2         S6       Dante Morse      198  Scarlette Fisher    205.0
3         S7    Kaiser William      219               NaN      NaN
4         S8   Madeeha Preston      201               NaN      NaN

9. Right Join Using Keys from Right DataFrame

In [81]:
#using right
pd.merge(student_data2,student_data1,on="student_id",how="right")

  student_id            name_x  marks_x            name_y  marks_y
0         S1               NaN      NaN  Danniella Fenton      200
1         S2               NaN      NaN      Ryder Storey      210
2         S3               NaN      NaN      Bryce Jensen      190
3         S4  Scarlette Fisher    201.0         Ed Bernal      222
4         S5  Carla Williamson    200.0       Kwame Morin      199
5         S6       Dante Morse    198.0  Scarlette Fisher      205

In [83]:
#using left
pd.merge(student_data1,student_data2,on="student_id",how="right")

  student_id            name_x  marks_x            name_y  marks_y
0         S4         Ed Bernal    222.0  Scarlette Fisher      201
1         S5       Kwame Morin    199.0  Carla Williamson      200
2         S6  Scarlette Fisher    205.0       Dante Morse      198
3         S7               NaN      NaN    Kaiser William      219
4         S8               NaN      NaN   Madeeha Preston      201

10. Merge Using Multiple Join Keys

In [84]:
pd.merge(student_data1,student_data2,on=["student_id","name"])

Empty DataFrame
Columns: [student_id, name, marks_x, marks_y]
Index: []