#### Pandas filter

1. Dataset Dimensions

Write a Pandas program to display the dimensions or shape of the World alcohol consumption dataset. Also extract the column names from the dataset.

In [4]:
import pandas as pd

data = {
    "Year": [1986, 1986, 1985, 1986, 1987],
    "WHO region": [
        "Western Pacific",
        "Americas",
        "Africa",
        "Americas",
        "Americas"
    ],
    "Country": [
        "Viet Nam",
        "Uruguay",
        "Cte d'Ivoire",
        "Colombia",
        "Saint Kitts and Nevis"
    ],
    "Beverage Types": [
        "Wine",
        "Other",
        "Wine",
        "Beer",
        "Beer"
    ],
    "Display Value": [
        0.00,
        0.50,
        1.62,
        4.27,
        1.98
    ]
}

df = pd.DataFrame(data)

print(df)

print("Rows :",df.shape[0])
print("Column :",df.shape[1])
print("column :",df.columns)

   Year       WHO region                Country Beverage Types  Display Value
0  1986  Western Pacific               Viet Nam           Wine           0.00
1  1986         Americas                Uruguay          Other           0.50
2  1985           Africa           Cte d'Ivoire           Wine           1.62
3  1986         Americas               Colombia           Beer           4.27
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98
Rows : 5
Column : 5
column : Index(['Year', 'WHO region', 'Country', 'Beverage Types', 'Display Value'], dtype='object')

2. Row and Column Slicing

Write a Pandas program to select first 2 rows, 2 columns and specific two columns from World alcohol consumption dataset.

In [15]:
df.iloc[0:2,0:2]

   Year       WHO region
0  1986  Western Pacific
1  1986         Americas

3. Random Sampling of Rows

In [17]:
df.sample(2)

   Year       WHO region                Country Beverage Types  Display Value
4  1987         Americas  Saint Kitts and Nevis           Beer           1.98
0  1986  Western Pacific               Viet Nam           Wine           0.00

4. Missing Value Handling

Write a Pandas program to find and drop the missing values from World alcohol consumption dataset.

In [19]:
df.isna().sum()

Year              0
WHO region        0
Country           0
Beverage Types    0
Display Value     0
dtype: int64

5. Duplicate Removal in 'WHO region'

In [20]:
df.drop_duplicates("WHO region")

   Year       WHO region       Country Beverage Types  Display Value
0  1986  Western Pacific      Viet Nam           Wine           0.00
1  1986         Americas       Uruguay          Other           0.50
2  1985           Africa  Cte d'Ivoire           Wine           1.62

6. Filtering by Year

Write a Pandas program to find out the alcohol consumption of a given year from the world alcohol consumption dataset.

In [27]:
print(df[df["Year"]==1985])
print("\n")
print(df[df["Year"]==1989])

   Year WHO region       Country Beverage Types  Display Value
2  1985     Africa  Cte d'Ivoire           Wine           1.62


Empty DataFrame
Columns: [Year, WHO region, Country, Beverage Types, Display Value]
Index: []

7. Filtering by Multiple Years

Write a Pandas program to find out the alcohol consumption details in the year '1987' or '1989' from the world alcohol consumption dataset

In [34]:
df[(df["Year"]==1987) | (df["Year"]==1989)]

   Year WHO region                Country Beverage Types  Display Value
4  1987   Americas  Saint Kitts and Nevis           Beer           1.98

8. Regional and Year Filtering

Write a Pandas program to find out the alcohol consumption details by the 'Americas' in the year '1985' from the world alcohol consumption dataset.

In [37]:
df[(df["Year"]==1985)|(df["Country"]=="Americas")]

   Year WHO region       Country Beverage Types  Display Value
2  1985     Africa  Cte d'Ivoire           Wine           1.62

9. Complex Filtering: Region and Country

Write a Pandas program to find out the alcohol consumption details in the year '1986' where WHO region is 'Western Pacific' and country is 'VietNam' from the world alcohol consumption dataset.

In [38]:
df[(df["Country"]=="VietNam")|(df["WHO region"]=="Western Pacific")]

   Year       WHO region   Country Beverage Types  Display Value
0  1986  Western Pacific  Viet Nam           Wine            0.0


11. Filtering by Year and Multiple Regions

Write a Pandas program to find out the alcohol consumption details in the year '1986' or '1989' where WHO region is 'Americas' or 'Europe' from the world alcohol consumption datase

In [41]:
df[((df["Year"]==1986 )|(df["Year"]==1989))   &        ((df["Country"]=="Americas")|(df["Country"]=="Europe"))]

Empty DataFrame
Columns: [Year, WHO region, Country, Beverage Types, Display Value]
Index: []